# Generated by Django 5.0.3 on 2024-05-25 13:58

import ckeditor.fields
import django.db.models.deletion
import phonenumber_field.modelfields
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Vacancies',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(max_length=50)),
                ('salary', models.IntegerField(blank=True, null=True)),
                ('type', models.CharField(blank=True, choices=[('Part time', 'Part Time'), ('Full time', 'Full Time'), ('Shift work', 'Shift Work')], max_length=50, null=True)),
                ('job_summary', models.TextField()),
                ('image', models.ImageField(blank=True, null=True, upload_to='vacancies/')),
                ('status', models.CharField(choices=[('active', 'Active'), ('deactive', 'Deactive')], default='Active', max_length=50)),
                ('responsibilities', ckeditor.fields.RichTextField()),
                ('requirements', ckeditor.fields.RichTextField()),
                ('working_condition', models.CharField(choices=[('remote', 'Remote'), ('in office', 'In office')], max_length=50)),
                ('view_count', models.IntegerField(default=0)),
            ],
            options={
                'verbose_name': 'Vacancy',
                'verbose_name_plural': 'Vacancies',
            },
        ),
        migrations.CreateModel(
            name='Projects',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('position', models.CharField(choices=[('Frontend developer', 'Frontend Developer'), ('Backend developer', 'Backend Developer'), ('Database administrator', 'Database Administrator'), ('Sales representative', 'Sales Representative'), ('Sales manager', 'Sales Manager'), ('Web developer', 'Web Developer'), ('senior travel assistant', 'Senior Travel Assistant'), ('Travel coordinator', 'Travel Coordinator')], max_length=300)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Project',
                'verbose_name_plural': 'Projects',
            },
        ),
        migrations.CreateModel(
            name='JobApplication',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('fullname', models.CharField(max_length=100)),
                ('email', models.EmailField(max_length=254)),
                ('mobile', phonenumber_field.modelfields.PhoneNumberField(max_length=128, region=None)),
                ('self_information', models.TextField()),
                ('cv', models.FileField(blank=True, null=True, upload_to='vacancies/')),
                ('vacancy', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='jobs.vacancies')),
            ],
            options={
                'verbose_name': 'Application',
                'verbose_name_plural': 'Job Application',
            },
        ),
    ]
