# Generated by Django 5.0.3 on 2024-08-08 17:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contact', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contactus',
            name='message',
            field=models.CharField(max_length=400),
        ),
        migrations.AlterField(
            model_name='contactus',
            name='message_az',
            field=models.CharField(max_length=400, null=True),
        ),
        migrations.AlterField(
            model_name='contactus',
            name='message_en',
            field=models.CharField(max_length=400, null=True),
        ),
        migrations.AlterField(
            model_name='contactus',
            name='message_ru',
            field=models.CharField(max_length=400, null=True),
        ),
    ]
